local objectname= "ad0_senegal_6" 
local featureDef	=	{
	name			= "ad0_senegal_6",
	world				="All Worlds",
	description				="Palm Tree",
	category				="Vegetation",
	object				="ad0_senegal_6.s3o",
	footprintx				=1,
	footprintz				=1,
	height				=30,
	blocking				=true,
	upright				=true,
	hitdensity				=0,
	energy				=50,
	metal				=0,
	damage				=221,
	flammable				=true,
	reclaimable				=true,
	autoreclaimable				=true,
	featurereclamate				="smudge01",
	seqnamereclamate				="tree1reclamate",
} 
return lowerkeys({[objectname] = featureDef}) 
